### ISSUE TITLE
Intermittent CSRF issue.

### ISSUE THREAD

**Issue by juur** [alextselegidis/easyappointments-wp-plugin#2]
Hi,

Occasionally when going to the page with the iframe on my WP install, I get an AJAX error pop-up -- the JS request is for `easyapp/index.php/appointments/ajax_get_available_hours`. 

Tracing this back through the code, the function `csrf_verify()` in [system/core/Security.php](https://github.com/alextselegidis/easyappointments-wp-plugin/blob/master/src/ea-vendor/system/core/Security.php) is failing with the `isset($_COOKIE[])` test - the `isset($_POST[])` passes. ([Line 151](https://github.com/alextselegidis/easyappointments-wp-plugin/blob/master/src/ea-vendor/system/core/Security.php#L151))

A reload of the page fixes this. Both WP and EA are under the same vhost/hostname/site, EA in a subdirectory. I can't find a pattern between browsers (occurs in Chrome, FF, IE, Edge on Windows and Chrome on Android). Trying with a fresh browser doesn't always give it. Logging out/in doesn't always give it.

Any ideas?

**Comment by alextselegidis** [comment]
Well, problems that randomly happening are really hard to be tracked down. I cannot really find the cause of the issue from your description but you can deactivate the CSRF checks by setting the `$config['csrf_protection'] = TRUE;` in `applications/config/config.php` file. 

The thing is that no one else reported such problems so it might just be a problem with your server configuration. If you have any news about the issue please post them here.
