### ISSUE TITLE
Wont install due to unexpected error

### ISSUE THREAD

**Issue by russellharrower** [alextselegidis/easyappointments-wp-plugin#3]
`An unexpected error occured in file /home/peterzapfella/public_html/wp-content/plugins/easyappointments/core/ValueObjects/Path.php (line 36): Invalid $path argument provided:`

I am not sure what else to tell you... I have the latest wordpress, and tried to add your plugin and got this when i went to settings/yourapp and clicked install

**Comment by alextselegidis** [comment]
Which URL/Path strings did you provide?
