### ISSUE TITLE
Cannot link wordpress to E!A installation

### ISSUE THREAD

**Issue by colorfill** [alextselegidis/easyappointments-wp-plugin#8]
Hi

I've got a problem with current E!A version + wordpress plugin (v1.0). After changing few lines in route.php i see both buttons: install and link. 

Wordpress data:
PATH:  /home/colorfil/domains/portal.vetsandpets.pl/public_html
URL: https://portal.vetsandpets.pl

E!A
PATH: /home/colorfil/domains/app.vetsandpets.pl/public_html
URL: https://app.vetsandpets.pl

after clicking LINK I got error:

> An unexpected error occured in file /home/colorfil/domains/portal.vetsandpets.pl/public_html/wp-content/plugins/easyappointments-wp-1.0.0/core/ValueObjects/Path.php (line 36): Invalid $path argument provided: /home/colorfil/domains/app.vetsandpets.pl/public_html/

**Comment by alextselegidis** [comment]
Can you check if the directory exists and if its writable by the user that runs PHP?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by colorfill** [comment]
I confirm: exist and have chmod 777

**Comment by alextselegidis** [comment]
Hmm this is strange, you can check yourself the validation that is made: 

`https://github.com/alextselegidis/easyappointments-wp-plugin/blob/master/src/core/ValueObjects/Path.php#L35`

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by colorfill** [comment]
We can close the issue - i've realized that wp plugin do not allow to target different subdomain. so I had to move everything to folder portal.vetsandpets.pl and make subdirs.
